version: '3'
services:
  app:
    container_name: nodeapp3
    restart: always
    build: .
    ports:
      - '8082:8082'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'