version: '3'
services:
  app:
    container_name: nodeapp1
    restart: always
    build: .
    ports:
      - '8081:8081'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'